controller_manager:
  ros__parameters:

    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ur3_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ur10_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ur3_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur10_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur3_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    ur10_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    ur3_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    ur10_forward_position_controller:
      type: position_controllers/JointGroupPositionController


ur3_joint_state_broadcaster:
  ros__parameters:
    frequency: 30

ur10_joint_state_broadcaster:
  ros__parameters:
    frequency: 30

ur3_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur3_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur3_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur3_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur3_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur3_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur3_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

ur3_forward_velocity_controller:
  ros__parameters:
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
    interface_name: velocity

ur3_forward_position_controller:
  ros__parameters:
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint

ur10_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
      - ur10_rail_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur10_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur10_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur10_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur10_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur10_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur10_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
      ur10_rail_joint: { trajectory: 0.2, goal: 0.1 }

ur10_forward_velocity_controller:
  ros__parameters:
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
      - ur10_rail_joint
    interface_name: velocity

ur10_forward_position_controller:
  ros__parameters:
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
      - ur10_rail_joint